USE [SNTBROKERv2]
GO

/****** Object:  Table [dbo].[MATRIZ1_TEMP_v2]    Script Date: 22/02/2021 17:55:46 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[MATRIZ1_TEMP_v2](
	[MATRIZ1] [char](500) NULL
) ON [PRIMARY]
GO


