-- CLAVE=SCON/ IDEMPRESA=5951/ HORA DISCRETIZADA=18:40/ PORC DESFASE=1362/ VOL MEDIO=8786/ VOLUMEN=119712
SELECT TOP 4 * FROM ALERTAS_V3

GO

drop table if exists ALERTAS_V3_P;

CREATE TABLE [dbo].[ALERTAS_V3_P](
	[CLAVE] [varchar](20) NOT NULL,
	[IDEMPRESA] [int] NOT NULL,
	[HORA_DISCRETIZADA] [varchar](10) NOT NULL,
	[PORC_DESFASE] [int] NOT NULL,
	[VOL_MEDIO] [int] NOT NULL,
	VOLUMEN [int] NOT NULL,
	[FECHA] [smalldatetime] NOT NULL
) ON [PRIMARY]

insert into ALERTAS_V3_P
SELECT
	convert(varchar(20), SUBSTRING(ALERTA, PATINDEX('%CLAVE=%',ALERTA)+6, PATINDEX('%IDEMPRESA=%',ALERTA)-PATINDEX('%CLAVE=%',ALERTA)-8)) as CLAVE,
	convert(int, SUBSTRING(ALERTA, PATINDEX('%IDEMPRESA=%',ALERTA)+10, PATINDEX('%HORA DISCRETIZADA=%',ALERTA)-PATINDEX('%IDEMPRESA=%',ALERTA)-12)) as IDEMPRESA,
	convert(varchar(10), SUBSTRING(ALERTA, PATINDEX('%HORA DISCRETIZADA=%',ALERTA)+18, PATINDEX('%PORC DESFASE=%',ALERTA)-PATINDEX('%HORA DISCRETIZADA=%',ALERTA)-20)) as [HORA_DISCRETIZADA],
	convert(int, SUBSTRING(ALERTA, PATINDEX('%PORC DESFASE=%',ALERTA)+13, PATINDEX('%VOL MEDIO=%',ALERTA)-PATINDEX('%PORC DESFASE=%',ALERTA)-15)) as [PORC_DESFASE],
	convert(int, SUBSTRING(ALERTA, PATINDEX('%VOL MEDIO=%',ALERTA)+10, PATINDEX('%VOLUMEN=%',ALERTA)-PATINDEX('%VOL MEDIO=%',ALERTA)-12)) as [VOL_MEDIO],
	convert(int, SUBSTRING(ALERTA, PATINDEX('%VOLUMEN=%',ALERTA)+8, LEN(ALERTA)-PATINDEX('%VOLUMEN=%',ALERTA)-7)) as VOLUMEN,
	FECHA
FROM ALERTAS_V3

GO

select * from ALERTAS_V3_P
